CREATE DATABASE Tuan5_Nhom3_124TCSDL204
GO
USE Tuan5_Nhom3_124TCSDL204
CREATE TABLE LOAIHANG
(
		MALOAIHANG 	    CHAR(10) PRIMARY KEY,
		TENLOAIHANG 	NVARCHAR(50)
)
CREATE TABLE KHACHHANG
(
		MAKHACHHANG 	CHAR(10) PRIMARY KEY,
		TENCONGTY	NVARCHAR(50) NOT NULL,
		TENGIAODICH 	NVARCHAR (50) NOT NULL,
		DIACHI 	NVARCHAR (50) NOT NULL,
		EMAIL	VARCHAR (40)  UNIQUE,
		DIENTHOAI	VARCHAR(11) NOT NULL UNIQUE,
		FAX 	VARCHAR(10) NOT NULL UNIQUE
)
CREATE TABLE NHANVIEN
(
		MANHANVIEN		CHAR(10) PRIMARY KEY ,
		HO				NVARCHAR(20) NOT NULL,
		TEN 			NVARCHAR(10) NOT NULL,
		NGAYSINH 		DATE,
		NGAYLAMVIEC 	DATE NOT NULL,
		DIACHI 			NVARCHAR(50),
		DIENTHOAI 		VARCHAR(11) UNIQUE,
		LUONGCOBAN		MONEY NOT NULL,
		PHUCAP			MONEY NOT NULL
)
CREATE TABLE NHACUNGCAP
(
   	MACONGTY			CHAR(10) PRIMARY KEY,
  	TENCONGTY 			NVARCHAR(50) NOT NULL,
  	TENGIAODICH 		NVARCHAR(50) NOT NULL,
 	DIACHI  			NVARCHAR(50) NOT NULL,
  	DIENTHOAI 			VARCHAR(11) NOT NULL UNIQUE,
 	FAX 				NVARCHAR(10) NOT NULL,
 	EMAIL 				VARCHAR(50) UNIQUE
)
CREATE TABLE MATHANG 
(	
		MAMATHANG 	CHAR(10) PRIMARY KEY,
		TENHANG 	NVARCHAR(50),
		MACONGTY 	CHAR(10) NOT NULL,
		MALOAIHANG 	CHAR(10) NOT NULL,
		SOLUONG 	INT,
		DONVITINH 	NVARCHAR(50),
		GIAHANG 	INT,
		FOREIGN KEY (MACONGTY)REFERENCES NHACUNGCAP(MACONGTY),
		FOREIGN KEY(MALOAIHANG)REFERENCES LOAIHANG(MALOAIHANG)
)
CREATE TABLE DONDATHANG
(
		SOHOADON 	INT IDENTITY PRIMARY KEY,
		MAKHACHHANG 	CHAR(10) NOT NULL,	
		MANHANVIEN	CHAR(10) NOT NULL,	
		NGAYDATHANG 	DATE NOT NULL,	
		NGAYGIAOHANG 	DATE,	
		NGAYCHUYENHANG 	DATE,	
		NOIGIAOHANG 	NVARCHAR(64) NOT NULL,
		FOREIGN KEY (MAKHACHHANG) 
		REFERENCES KHACHHANG (MAKHACHHANG),
		FOREIGN KEY (MANHANVIEN) 
		REFERENCES NHANVIEN (MANHANVIEN)
)
CREATE TABLE CHITIETDATHANG
(
  	SOHOADON 		INT IDENTITY,
  	MAHANG 			CHAR(10),
	GIABAN			MONEY,
	SOLUONG			INT,
	MUCGIAMGIA		FLOAT DEFAULT 0,
 	PRIMARY KEY (SOHOADON, MAHANG),
	FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAMATHANG),
	FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON)	
)

